export type StepName = "collecting" | "extracting" | "finalizing";

export const DOMAIN_ERROR_CODES = {
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  JOB_NOT_SUCCEEDED: "JOB_NOT_SUCCEEDED",
  JOB_NOT_CANCELABLE: "JOB_NOT_CANCELABLE",
  INVALID_IDEMPOTENCY_KEY: "INVALID_IDEMPOTENCY_KEY",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_INPUT: "INVALID_INPUT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];

export const WARNING_CODES = {
  PARTIAL_EXTRACTION: "PARTIAL_EXTRACTION",
  MISSING_FIELDS: "MISSING_FIELDS",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  ARTIFACT_NOT_STORED: "ARTIFACT_NOT_STORED",
} as const;

export type WarningCode = (typeof WARNING_CODES)[keyof typeof WARNING_CODES];

export type ConfidenceLevel = "high" | "medium" | "low";
